title: LightFormer Light-Oriented Global Neural Rendering in Dynamic Scene
email: minervas@qunhemail.com
description: Website for LightFormer
# baseurl: "/MINERVAS" # the subpath of your site, e.g. /blog
baseurl: "." # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']

# Google Analytics
google_analytics: G-52GJBKGE0J
